cr:
  create: true
  namespace: istio-system
  spec:
    auth:
      strategy: anonymous
    external_services:
      prometheus:
        url: "http://kube-prom-stack-kube-prome-prometheus.monitoring:9090/"
      grafana:
        enabled: true
        # Grafana service name is "grafana" and is in the "telemetry" namespace.
        internal_url: "http://kube-prom-stack-grafana.monitoring.svc.cluster.local:80"
        dashboards:
          - name: "Istio Service Dashboard"
            variables:
              namespace: "var-namespace"
              service: "var-service"
          - name: "Istio Workload Dashboard"
            variables:
              namespace: "var-namespace"
              workload: "var-workload"
          - name: "Istio Mesh Dashboard"
          - name: "Istio Control Plane Dashboard"
          - name: "Istio Performance Dashboard"
          - name: "Istio Wasm Extension Dashboard"
